### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by sugan0tech** [sugan0tech/Event-Manager#61]

**Comment by Rajdeep1311** [comment]
I would like to help...if I get the details

**Comment by sugan0tech** [comment]
Yeah sure!!, for this project we are currently in need of a proper documentation for API's, Class structure explanation.

**Comment by sugan0tech** [comment]
you can the refer the format [here](https://github.com/khoubyari/spring-boot-rest-example)

**Comment by Rajdeep1311** [comment]
And info about the API ?

**Comment by sugan0tech** [comment]
as same as given in the above repo.
